apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
 strategy:
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
    app: sample-app
 template:
  metadata:
    labels:
      app: sample-app
  spec:
   containers:
    - name: sample-app
      imagePullPolicy: Always
      image: jedineeper/sample-app:latest
      resources:
       limits:
        memory: "128Mi"
        cpu: "500m"
      ports:
       - containerPort: 8000
      env:
        - name: EXAMPLE
          valueFrom:
            configMapKeyRef:
              name: sample-app
              key: example-var
