apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  ports:
    - name: sample-app
      protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    app: sample-app
  type: LoadBalancer
